// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dbstore

import (
	"time"
)

type Book struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Author string `json:"author"`
	Stock  int32  `json:"stock"`
}

type Bookborrow struct {
	ID         int64     `json:"id"`
	Borrowdate time.Time `json:"borrowdate"`
	Returndate time.Time `json:"returndate"`
	UserID     int64     `json:"user_id"`
	BookID     int64     `json:"book_id"`
	Status     string    `json:"status"`
}

type User struct {
	ID       int64  `json:"id"`
	Role     string `json:"role"`
	Username string `json:"username"`
	Password string `json:"password"`
}
